### ISSUE TITLE
Cannot find module @svelte-drama\swr\_memoize

### ISSUE THREAD

**Issue by FraWolf** [svelte-drama/swr#1]
Hello, when I try to use `refreshInterval` it says:

Cannot find module 'XXXXX\node_modules\@svelte-drama\swr\_memoize' imported from XXXXX\node_modules\@svelte-drama\swr\_plugins\refresh-interval.js

Svelte version: ^3.48.0 (latest)

**Comment by WaltzingPenguin** [comment]
This should be resolve as of v0.2.6
