### ISSUE TITLE
Return more functions from .live?

### ISSUE THREAD

**Issue by olehmisar** [svelte-drama/swr#10]
I'd like to not repeat key when using `.refresh`

Current behaviour:
```ts
$: data = model.live({ id })

// later in the code
model.refresh({ id })
```

Would you consider this API?
```ts
$: data = model.live({ id }))

// later in the code
// no need to specify `{ id }` because it is defined when `data` is created
data.refresh() 
```

**Comment by olehmisar** [comment]
Looks like it is already implemented as `data.refresh()` but it is not documented, so I did not find it initially.

**Comment by WaltzingPenguin** [comment]
Which functions would you want to see returned?  I can see the use case of `refresh` here.  `delete` when called on a key with a live subscription is more or less the same as refresh.  `fetch` doesn't make sense to me here.  `update` is dangerous on a store, it's pretty easy to accidentally treat the store as writable and the function signatures do not match.

**Comment by olehmisar** [comment]
I would start with `.refresh()` and add other functions in the future if there will be any requests/use cases. You can clearly see the use case for `.refresh()`, so that's why I am asking
