### ISSUE TITLE
Dump/load state to/from localStorage

### ISSUE THREAD

**Issue by olehmisar** [svelte-drama/swr#13]
I'd like to achieve very fast page refresh by storing state to `localStorage` and loading it after user reloads page. Is there any way to achieve it? I cannot figure it out from the README.

As I understand, it should be doable by customizing the `cache` here but I don't see a way to pass it down from user side. https://github.com/svelte-drama/swr/blob/6abe0e4a4d21482957031edf19bfa4fe84f9e0b1/src/lib/swr/internals.ts#L19

**Comment by WaltzingPenguin** [comment]
Information is loaded from IndexedDB.  Operations on IndexedDB are async while operations on `localStorage` are blocking, so there will be a very slight delay.  For nearly all use cases, I can't imagine this making a difference.

Currently undocumented, the cache is cleared if the user reloads the page.  To test actual startup times for returning visitors, open a new tab and navigate to the website.  If you type in the same address as the page you are currently viewing, most browsers will treat that as a reload.

**Comment by olehmisar** [comment]
It does not matter if it's localStorage of IndexedDB. I need a way to dump/load data when user refreshes the page for an instant refresh. Is it possible to do?

In React swr, it is implemented using a cache provider: https://swr.vercel.app/docs/advanced/cache#localstorage-based-persistent-cache

**Comment by WaltzingPenguin** [comment]
If a user specifically requests a page to be reloaded, it is normal for browsers to ignore cache and make all requests again.  However, if a user navigates to a cached page later, then the cache headers are respected.  This library mimics that same pattern.  Without some ability to clear cache, there is the risk of a code error putting users into a completely unrecoverable state.

Can you explain the use case further where you specifically want Ctrl + R to serve from cache?  As noted, things are loaded from cache for return visitors.  Just not specifically for reloads.

**Comment by olehmisar** [comment]
yes, you are right. I need it for returning visitors to simulate app-like behavior with instant open times
