### ISSUE TITLE
Loading/error indicator

### ISSUE THREAD

**Issue by olehmisar** [svelte-drama/swr#15]
How do I know if `fetcher` is currently loading or if it threw an error or not? Using `$data === undefined` is not a good indicator of loading state because `undefined` may be a valid value

**Comment by WaltzingPenguin** [comment]
As a style convention, I would not recommend initializing values to `undefined`.  `null` is generally preferred.

**Comment by olehmisar** [comment]
Thanks, but that does not address my issue. I need to show an indicator that data is being loaded or re-loaded(when I call `.refresh`; note that data is NOT `undefined` when re-loading, so I cannot use `$data === undefined`). In react's swr, there are separate `isLoading`, `isValidating`, and `error` values returned from `useSWR`. E.g.,:
```ts
const { data, error, isLoading, isValidating } = useSWR(...)
```

Is it possible to do something like this with your swr?

**Comment by WaltzingPenguin** [comment]
It's possible this library needs to surface more fine-grained control as building blocks.  For this specific case, `refresh` returns a promise.  While that promise is unresolved, a request is currently in flight.

For building UIs handling loading and error states, I would recommend trying the sister library [Svelte Suspense](https://github.com/svelte-drama/suspense) on top of SWR.
