### ISSUE TITLE
Non-string keys?

### ISSUE THREAD

**Issue by tv42** [svelte-drama/swr#3]
Hi. I'm exploring my options for managing data loading that has outgrown SvelteKit's `load` mechanism. Your library seems to be very relevant for that.

However, I'm just simply GETting URLs. For example, one of the data sources I need for the pages is a Meilisearch search query, which really is best done as a POST, with a JSON body.

I *could* encode everything into a string key with something like `JSON.stringify`, but that seems silly, just to parse it again in the fetcher. And I'd lose all benefits of Typescript doing that.

Looking at https://github.com/svelte-drama/swr/search?q=key , the only thing swr seems to use really use the `key` argument for is as a cache key: https://github.com/svelte-drama/swr/blob/c010139e2f7297a08fd48584115a69d648f20c7e/src/lib/_cache.ts#L11

The Typescript `Map` type is on the surface capable of handling non-string keys, but turns out the comparison function makes that nothing but a footgun: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#key_equality

Any thoughts here?

I'm thinking my key type would most naturally look something like

```
export type DataKey =
  | {
    type: "search";
    meili: {
       index: string;
       query: string | null;
       options?: SearchParams;
    };
  }
  | {
    type: "apples";
    count: number;
  }
  | {
    type: "oranges";
    juicy: boolean;
  }
```

(Not really sure at this point if I'm supposed to have an swr instance per data source, or what. If I'm better off with multiple swr instances, that just moves each member of the union into its own swr; the complex query case remains.)

**Comment by WaltzingPenguin** [comment]
Remember that objects are not equal in JS.
```js
{ type: "apples" } !== { type: "apples" }
```

Either object could be used as a key in a Map, but they would be different keys.  You would have to keep a reference to the exact object used, but if you can do so easily you have no need for this library.  The types are declared deliberately to avoid this pitfall.

In most cases, the key will simply be the URL you are accessing.  In the instances where that is not applicable (your example POST request), you will need a way to deterministically create a key for those requests that is strictly equal (`===`) and does not need references to previous requests.
