### ISSUE TITLE
System is not making new requests

### ISSUE THREAD

**Issue by psociety** [svelte-drama/swr#5]
Thank you for creating this package!!

I've set it up but seems like i'm missing something. 
My expectation was that everytime swr was fired, it would return the cached data (if available) while making the request in bg to update it. But that's not happening.
The system makes 1 request and then always resolves the cached data without making the request in background.

This is how i call swr:
```js
const { data, error, refresh, update } = swr(route, {
          fetcher: (route) => fetch(BASE_URL + route, request).then((r) => r.json()),
});
```

What i'm missing out?

Edit: Oh, so i have to also set `maxAge: 0` so cached data is still used once and refreshed in bg.

**Comment by WaltzingPenguin** [comment]
Correct.  The default assumption is that data can be safely cached but that can be bypassed by setting `maxAge` or manually marking data as stale.
