### ISSUE TITLE
revalidateOnFocus, revalidateOnReconnect?

### ISSUE THREAD

**Issue by olehmisar** [svelte-drama/swr#9]
Are there plans to add `revalidateOnFocus` and `revalidateOnReconnect`? I can help adding these options

**Comment by WaltzingPenguin** [comment]
`revalidateOnFocus` should no longer be necessary.  The use of BroadcastChannels in the most recent rewrite should keep tabs in sync, even when hopping between tabs and editing data.

`revalidateOnReconnect` is more or less just part of the default now.  Stores with active subscribers will refetch data if `maxAge` is exceeded when the network transitions to "online".

If you had specific use cases for those that is no longer covered, it would be interesting to discuss them.

**Comment by olehmisar** [comment]
i've been using this swr for over 2 weeks and i don't fee that I need these functions
